#!/bin/bash
shopt -s extglob
set -o errtrace
set -o errexit

echo "Need to install git (brew install git | apt-get install git)"
echo "=> press enter"
read

if [ "$(uname)" = "Darwin" ]; then
	brew install git
else
	apt-get install -y git
fi

if [ ! -x `which vim` ]; then
	if [ ! "$(uname)" = "Darwin" ]; then
		apt-get install -y vim-nox
	fi
fi

cd ~
mkdir -p ~/bin


# enables ctrl-p like search in a terminal
# see bashrc for binding
curl -ssl3 https://raw.githubusercontent.com/jeetsukumaran/fuzzysnake/master/bin/fz > ~/bin/fz && chmod 0755 ~/bin/fz

echo "Need to install ipython, pyzmq, tornado and pythonpy"
sudo pip install ipython pyzmq tornado pythonpy

git clone --recursive git@github.com:sherzberg/dotfiles.git
cd dotfiles

# Setup sym links
for i in bashrc bash_profile gitconfig gitignore vimrc vim tmux.conf i3 i3status.conf xsession
do
	rm -rf $HOME/.$i;
	ln -s $HOME/dotfiles/$i $HOME/.$i;
done;

ln -s $HOME/dotfiles/gitignore $HOME/.hgignore

mkdir -p ~/.config/awesome
rm -rf ~/.config/awesome
ln -s $HOME/dotfiles/awesome $HOME/.config/awesome

rm -f ~/.config/redshift.conf
ln -s $HOME/dotfiles/redshift.conf ~/.config/redshift.conf

mkdir -p ~/.pip
ln -s ~/dotfiles/pip.conf ~/.pip/pip.conf

if [ "$(uname)" = "Darwin" ]; then
	ln -s $HOME/dotfiles/tmux/mac_tmux ~/.tmux
else
	ln -s $HOME/dotfiles/tmux/linux_tmux ~/.tmux
fi

echo -n "Would you like to configure your git name and email? (y/n) => "; read answer
if [[ $answer = "Y" ]] || [[ $answer = "y" ]]; then
    echo -n "What is your git user name => "; read name
    git config --global user.name "$name"
    echo -n "What is your git email => "; read email
    git config --global user.email "$email"
fi

vim +BundleInstall +qall
echo "Installation complete! Run $ source ~/.bashrc"
