#!/bin/bash

# Need to make this portable
if [[ `uname` == "Darwin" ]]; then
	brew install git
else
	apt-get install git
fi

exit

cd ~

git clone --recursive git@github.com:sherzberg/dotfiles.git
cd dotfiles

# enables ctrl-p like search in a terminal
sudo pip install -e git+https://github.com/jeetsukumaran/fuzzysnake.git#egg=fuzzysnake

# Setup sym links
for i in bashrc gitconfig gitignore vimrc vim tmux.conf i3 i3status.conf xsession
do
	rm -rf $HOME/.$i;
	ln -s $HOME/dotfiles/$i $HOME/.$i;
done;

ln -s $HOME/dotfiles/gitignore $HOME/.hgignore

mkdir -p ~/.config/awesome
rm -rf ~/.config/awesome
ln -s $HOME/dotfiles/awesome $HOME/.config/awesome

rm -f ~/.config/redshift.conf
ln -s $HOME/dotfiles/redshift.conf ~/.config/redshift.conf

mkdir -p ~/.pip
ln -s ~/dotfiles/pip.conf ~/.pip/pip.conf

if [ "$(uname)" = "Darwin" ]; then
	ln -s $HOME/dotfiles/tmux/mac_tmux ~/.tmux
else
	ln -s $HOME/dotfiles/tmux/linux_tmux ~/.tmux
fi

vim +BundleInstall +qall
echo "Installation complete! Run $ source ~/.bashrc"
