#!/bin/bash

sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade

sudo apt-get install vim-nox
sudo apt-get install python-dev python-pip

sudo pip install --upgrade pip virtualenv wheel virtualenvwrapper
